// Custom shader file for dm_xmas.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

dm_xmas/297C41D8B20E9594B9943FDD8D2EA83A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_carpet4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/CCE4C5FF13D6878BA679BCEB2E04B73B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_carpet2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/7401F41A7EE841AE38B2EA9B9F024F23
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_green.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/0BA5CDD00C9CA672E4D716DFF42BDC75
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_dirt/dirt_coal1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/B8BF6D929A9B42104157B94CF5D53D1F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_pictures/girly.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/07CC022B4234F5D11E87EC59C83D8262
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/825A717D49AA28803D0B46AC8A76A3B1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/3EFAE889FB7842381ACD2DE51D88247E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/3880D22460CAE3BECE2294F205326517
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/F8899DEE87E924E30714AF02FC619468
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.16406
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/E354D922F3BC7A3DBA37954BF8D1EA70
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.16406
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.60156
	}

	{
		map textures/sg_cloth/cloth_smooth_leather.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/A0E72EB3E37BAA9AD4B15CD1FEF74D3C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_safe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/77513108DC8E40BBD5BC47C54B5C215F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_metal/metal_rusty2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/B7BEA378EE374C150B81140C4B23C4F7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_metal/metal_rusty2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/5581D1B65D92F26CC399F1D71460EC48
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_cloth/cloth_carpet1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/FAB4B11AD6CCC5DF393D50FA37FA7354
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood1/wood_treetropic.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/1AA2D77DA4C3BEDC307432A061FA50FF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0023.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood1/wood_treetropic.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/1EAA17039D2BE84EB617C1B2FCD5CAD2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood1/wood_treetropic.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/68C1AE24B571B1FDA0E9617D97C03DB8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0031.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/E10DB35A2FCF3853C883D7BA9DB07452
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0039.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0044.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/A9521F54FD429E4BC37CD18901A95465
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0029.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/66EC0DBBB7E27242FF59973BD42131CB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0027.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/8D3A10BC90BE5DDBDEBE13535DF8C95B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/DBB96D8C902BA0532B5BAB3624FBB855
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0042.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0043.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/9D9ABF94161AB77EE3DBE819BB792B9F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0038.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/C3C57698D3711990BCE7F77FD9EE7179
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0029.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0032.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/CA437E91F2493B5C84A5CD608F2092F3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0038.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/C4F013EB58A9F45E5B5B4085E2251273
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0028.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0029.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/6BFD00A0B027E46C4AE3D54E62558960
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0039.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/15AA3629CFC4145AF92ABE8C9059D464
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0027.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/514C43C35E8CBA86B1CEF7B0AEB49B7B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0029.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0030.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/7CDD17AA0D925A37F1F0D29A8D4E2108
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0037.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0038.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/BC1B51468A478921AB69FB4D443D815D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0040.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0041.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/EB916CE376C725FAA48D55037E02C048
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/32EB75582AA6EF0420D03E90C25FEC1C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0033.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0036.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood3/wood_logs.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/57362B0B549210E15390F062E513FB38
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0032.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0033.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood2b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/3803D118EE85A9D5C1F91B98508866B5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0025.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0026.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood1/wood_door14b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/9539DD6056B01A46D5482FDED19CFFF5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/EC4E11FE62B149C51A943060D3348126
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.25781 0.00000
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/D4E52B2329C279252B5B567FD6A1CD6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/43AC6DD8A018313B9929C04F7FD47663
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/37128D9119FA83FC6568DB9D339E171A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.25000 0.02344
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/26F82A0B5F2B67F001BBDEA4D3258AAF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/42222792434665CAFCE8BC255D7C4029
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/252419864FD4E4A15A0622D981004FF0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/sg_stone/stone_stonewall3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/F58462BC5879A777200DCB6998B9347F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0035.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/F88B8B462ADF7F57775757CF534B0CB4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0034.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/3E1B43481566A3250BF2CCFD96C59175
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0027.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/FC2A8CEAE479F52FD221B83B55D0291D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/sg_wood2/wood_wood3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/40DAD12CB66E3AEBAF430EBF92DAB9EA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0029.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0030.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood13b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/4F071F2AB6371A9023BB878D10D2A6CD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0031.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood18b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/979EA451E2D1BED5448A3D974A7597CB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_wood18b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/E643222D62A937776E718F5AF8FC0A1B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/961A54ADCC27A7DA40B217E10C4F29CB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/912630E2A86A1FBBC8C79C2DDBE78AB4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/A5642AB060DC354E047C2AE0E455A7E4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/4FD011AF3D27D49E030BDA118FE7418B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/A342C20FBCDE4AC997A6E4B22499C59D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0026.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/CF5A511498301EFA2B6FC0B7DD2439E2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/3937209CD251D9575D5352AFDC1C6117
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/9C331EC95AAA557CD8C9F6F4D76EDC5F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/71951784FE84B79F83016907443B5614
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/2CF7DD146B1C5A825112E159F7485E91
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/E470111696C88A8EAF2DAB6B5A1E358C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0025.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0026.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/C9BCACDB0E8311E3084834EA2E5DCAD7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}
	{
		map maps/dm_xmas/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/CDE6E858B82B724AA39B3DB15F74C987
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/C4738D133AF04F6788ED0C6AE9CC6892
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/44ED2E0681244733D48F72A63C1E5238
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/0067D6E31CF54DD0086A078953CC4425
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0026.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

dm_xmas/F6B9CAB86B6F508AAD259958AD433E0C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/dm_xmas/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 6
		tcGen lightmap
	}

	{
		map textures/sg_wood2/wood_filling7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

